### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by PyvesB** [eclipse/wildwebdeveloper#127]
Hello,

When trying to update or reinstall Wild Web Developer from scratch, I am getting the following error:
```

An error occurred while collecting items to be installed
  session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
  No repository found containing: osgi.bundle,org.eclipse.wildwebdeveloper,0.1.0.201902011810
  No repository found containing: org.eclipse.update.feature,org.eclipse.wildwebdeveloper.feature,0.1.0.201902011810
```
Is something wrong with the p2 repository setup?

Thanks in advance for your help.

Cheers,

Pyves

**Comment by mickaelistria** [comment]
It can be an issue with the remote or local cache. Please try again a bit later. Make sure you restart the IDE to wipe out the local cache of p2 metadata.

**Comment by PyvesB** [comment]
The issue is still persisting. I have restarted the IDE as per your advice, but it has not solved the problem.

**Comment by mickaelistria** [comment]
I just updated to latest build from http://download.eclipse.org/wildwebdeveloper/snapshots and didn't see any issue.

**Comment by PyvesB** [comment]
I finally managed to reinstall it by deleting the entire p2 repository cache folder from my Eclipse installation. Not sure what happened here, but at least problem solved.

**Comment by pbodnar** [comment]
Hi, this issue still persists:

> No repository found containing: osgi.bundle,org.eclipse.wildwebdeveloper,0.5.12.202009212151

So is it a generic Eclipse bug, or this project's issue? I'm also getting this for various 'org.springframework.ide' bundles... Why does Eclipse offer an update of something that can't be download in the very next step?

I tried to remove the cache folder from both '.p2\org.eclipse.equinox.p2.core' and '.eclipse\org.eclipse.oomph.p2' in USER_HOME, restarted Eclipse with '-clean', yet I'm getting the very same errors... (Eclipse 2020-06)

**Comment by mickaelistria** [comment]
@pbodnar How do you install things? Which repos do you have available?

**Comment by pbodnar** [comment]
@mickaelistria, the WWD seems to be part of the "Eclipse IDE for Enterprise Java Developers". I installed this Eclipse version 2020-06 via the Eclipse Installer. And on one computer, the upgrade to 2020-09 was working nicely, while on the other one I'm getting the problem described above.

Historically, I have different sites (equal to "repos"?) listed on both PCs (much more on the problematic one, because using it much more), so the culprit will be possibly somewhere among them? But I have no idea how to debug this stuff, Eclipse GUI doesn't seem to be much helpful in this regard and I'm afraid the documentation to p2 will be readable for insiders only...

For now, I have upgraded without WWD and regarding Spring Tools, I have upgraded them by their re-installation...
