### ISSUE TITLE
Custom snippets/templates

### ISSUE THREAD

**Issue by vk011** [eclipse/wildwebdeveloper#140]
Hi,
The extension is great, but is it possible to add custom snippets to it? I have snippets set for built in JavaScript support but they are not showing because I guess the files have to be opened with generic text editor.

So any way to connect JavaScript snippets to this, or add snippets just for the extension?

**Comment by mickaelistria** [comment]
Do you mean snippets defined with Eclipse JSDT ?

**Comment by vk011** [comment]
I don't have the JSDT plugin installed if that is what you mean, I have Eclipse Web Developer tools installed if it makes a difference.

Anyway what I meant by "snippets defined" is at Window > Preferences > JavaScript > Editor > Templates

Can those snippets be somehow read by this extension, or can I somehow create snippets for this extension which is fine as well.

**Comment by mickaelistria** [comment]
> Anyway what I meant by "snippets defined" is at Window > Preferences > JavaScript > Editor > Templates

This preference page is not provided by Wild Web Developer. I guess you have JSDT installed.
For the moment, Wild Web Developer doesn't host a snippet registry. And I don't think it's the priority of any of the current contributors to implement that. But if you want to contribute such, it would be welcome, especially if snippets do reuse a generic and common format that is understood by many tools already.
We won't bind hardly Wild Web Developer to JSDT, but if we can reuse some of its internal files because they're in a portable and generic format, we can try it; or we can try to adopt another technology for snippets.

But before getting started in implementing snippets in wild web developer, the question is whether they could make more sense in the language server. Wild Web Developer uses https://github.com/theia-ide/typescript-lsp under the hood, and usually, more features related to content of edition assist (such as snippets) would better be placed upstream in the typescript-lsp as it will drive to simpler UX and more reusability.

**Comment by mickaelistria** [comment]
No news for a while, let's close.
