### ISSUE TITLE
WildWeb not proposed for xml files by marketplace client

### ISSUE THREAD

**Issue by akurtakov** [eclipse/wildwebdeveloper#181]
Platform defines the xml content type although not providing any editor for xml files. It's not wildweb issue but I open it here for brainstorming as it may require multiple projects to be changed for this to work.
Btw, same happens for html files.
Mickael, wdyt? What should we look for? Having wildweb being proposed for html/xml files will make the userbase grows a lot.

**Comment by jabby** [comment]
Hello, if I understand correctly, platfom defines xml and html content. 
By doing this definition, the marketplace client will not looking for a plugin supporting the corresponding extension.

For information, the list of declared extensions in marketplace entry is: 

* css
* dtd
* htm
* html
* js
* json
* jsx
* less
* sass
* scss
* ts
* tsx
* xml
* xsd
* xsl (I updated this one because the declaration was `fileExtension.xsl` instead of `fileExtension_xsl`
* yaml
* yml

**Comment by mickaelistria** [comment]
Does Platform add support for HTML files? Or does it come from anywhere else?
In any case, it's a general issue of Marketplace discovery: it's only triggered when nothing is available for a given file; and it's usually what's desired otherwise people who're using Wild Web Developer would often see popup to install WebTools when they open the file.
Can you please open an issue to MPC about this brainstorming, as it's probably where the resolution should take place?

**Comment by akurtakov** [comment]
Time to close this one after nothing happened in years.
