### ISSUE TITLE
`Right-click > Debug As > Firefox` fails to start debug session

### ISSUE THREAD

**Issue by akurtakov** [eclipse/wildwebdeveloper#245]

**Comment by mickaelistria** [comment]
Can you please export your launch configuration as a .launch file and push content here?
Also, what happens if you restart your IDE. Both @AObuchow and I have observed some failure on the 1st few attempts and then success on following attempts...

**Comment by akurtakov** [comment]
I don't have launch configuration. Right-click on html file and Debug As -> Firefore. Creating launch configuration works.

**Comment by mickaelistria** [comment]
Thanks for the clarification.
I think it's indeed a glitch in the launch shortcut that doesn't properly prepare the Launch Configuration (which is volatile and not visible in UI, yet existing internally).

**Comment by AObuchow** [comment]
> I don't have launch configuration. Right-click on html file and Debug As -> Firefore. Creating launch configuration works.

Right-click Debug As -> Firefox isin't implemented yet. When I tried associating a launch configuration with an html file (via right-click -> Properties -> Run/Debug settings), the only option given is "Running Firefox Debugger". 

Thus, I believe you were attempting to attach to a Firefox debug session (I don't know why it defaults to attach rather than launch, **this is a bug IMO**)

For a "running firefox debugger" launch, Firefox must already be running for Eclipse to attach to the instance. 
- To verify this was the issue, open Firefox, go on `about:debugging` and click on **Enable debugging of add-ons** (needed for remote debugging).  
- Then close Firefox and launch it with `firefox -start-debugger-server`. 
- Finally, in Eclipse with WWD installed, click the debug icon -> Debug Configurations... and make sure the port is set to 6000 before hitting debug. Eclipse should give confirmation that the launch was able to attach in the progress view.

**Comment by mickaelistria** [comment]
> Right-click Debug As -> Firefox isin't implemented yet.

Actually it is, as the plugin.xml defines a Launch shortcut.
To see it, you can install Wild Web Developer in an Eclipse IDE instance which has for instance JDT installed. Some of JDT code will enable the "Debug As" in context-menu for HTML file.

**Comment by AObuchow** [comment]
> > Right-click Debug As -> Firefox isin't implemented yet.
> 
> Actually it is, as the plugin.xml defines a Launch shortcut.
> To see it, you can install Wild Web Developer in an Eclipse IDE instance which has for instance JDT installed. Some of JDT code will enable the "Debug As" in context-menu for HTML file.

Ahh okay thank you for the correction. I had previously gotten the context-menu to appear but haven't been able to do since. Now I know why.

My theory still stands that @akurtakov was trying to attach to a Firefox debug session rather than launch a Firefox debug instance due to confusing UI.

**Comment by mickaelistria** [comment]
> My theory still stands that @akurtakov was trying to attach to a Firefox debug session rather than launch a Firefox debug instance due to confusing UI.

Alex was doing Right-click > Debug As > Firefox and expecting Firefox to start a debug session.
The Launch Shortcut may have done something different, or done the right thing incorrectly; but in any case, it seems to be what needs a fix (more than Alex ;).

**Comment by AObuchow** [comment]
> > My theory still stands that @akurtakov was trying to attach to a Firefox debug session rather than launch a Firefox debug instance due to confusing UI.
> 
> Alex was doing Right-click > Debug As > Firefox and expecting Firefox to start a debug session.
> The Launch Shortcut may have done something different, or done the right thing incorrectly; but in any case, it seems to be what needs a fix (more than Alex ;).

Yes I totally agree (I was blaming the UI not Alex).
It's misleading how the debug "title" get's truncated to just "Firefox" rather than "Running Firefox..." as seen in this photo 
![image](https://user-images.githubusercontent.com/10300119/64285118-171e9600-cf29-11e9-80d6-c9486d8bf054.png)

However, I believe this might be worthy of a new issue if it's something that can be fixed.
