### ISSUE TITLE
ReactJS syntax not working

### ISSUE THREAD

**Issue by syedhamzamohiuddin** [eclipse/wildwebdeveloper#270]
files with .js extention report errors when React's syntax is used
![Screenshot from 2019-09-28 17-14-31](https://user-images.githubusercontent.com/35479390/65816392-3fda3880-e214-11e9-9fb0-7e22134b09d9.png)

**Comment by rombert** [comment]
I hit the same thing and changed the files to have the jsx extension.

**Comment by syedhamzamohiuddin** [comment]
I used "npm install" .
Then I tried changing all files with react syntax to jsx and error dissappeard in the ide but then the terminal (on which ''npm start " is running) shows an error saying index.js cannot be found ad I made it into index.jsx .

**Comment by gkostov** [comment]
But is there a way to have React support in .js files? I tried fiddling with the "Content Types" section but it did not help. There is the "Language Servers" section which offers to "associate content types with a Launch configuration which starts a language server ..." but I don't know how to setup that configuration.

**Comment by mickaelistria** [comment]
> But is there a way to have React support in .js files? 

I don't think there is. What's the issue using jsx extension?

Anyway, more than 3 years without activity here, let's close.

**Comment by gkostov** [comment]
Problem is probably just personal preference - I tend to put .jsx on files which export Components (the file is all about the JSX inside), while I may have some .js file just touching on a bit of JSX here and there, but being pure JS otherwise.
Anyway, that does not appear to be a problem these days as my .js files handle JSX just fine. Not sure what or when's been updated but it works great, so thanks for that! :)
