### ISSUE TITLE
Autocomplete in angular .html does not prepend missing part of property

### ISSUE THREAD

**Issue by megaza** [eclipse/wildwebdeveloper#279]
Wild Web Developer: 0.7.0.201910102046

Autocomplete in .html works but after selecting title from popup results into `{{t}}` > `{{ttitle}}`. It does not prepend missing characters, so the test should pass referencing autocomplete on property from a object, `{{person.n}}` > `{{person.nname}}`.

Autocomplete in .ts does have two autocomplete options, one with prepending missing characters, and one with full name prepend (which is the only option in .html autocomplete).

![autocomplete-ts](https://user-images.githubusercontent.com/6707617/66639392-0abbe600-ec17-11e9-8079-d137bfb1204a.png)

**Comment by mickaelistria** [comment]
I can reproduce it easily for HTML in a test case, see https://github.com/eclipse/wildwebdeveloper/pull/280 . Debugging this test, I see the completionItem we receive is
```json
{"jsonrpc":"2.0","id":"2","result":[{"label":"title","kind":10,"detail":"property","sortText":"title","textEdit":{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":7}},"newText":"title"}}]}
```
according to the spec, this is an instruction to insert `title` on character 7, without deleting anything. So Eclipse IDE (LSP4E) is doing the right thing, and the issue comes from the language server not passing the right range.

**Comment by mickaelistria** [comment]
I opened https://github.com/angular/vscode-ng-language-service/issues/417 for the language server.

**Comment by mickaelistria** [comment]
This seems to be working better since 0.8.1 and recent update of Angular language server.
