### ISSUE TITLE
Errors in eclipse problem view are not displayed using local typescript 2.6.2

### ISSUE THREAD

**Issue by megaza** [eclipse/wildwebdeveloper#286]
Wild Web Developer: 0.7.1.201910151353

Project uses local typescript 2.6.2.
Code completion and jump to implementation works but errors are not displayed "Property xyz does not exist on type XYZ". LSP4E log:
```
[t=1571464481024] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"14","error":{"code":-32603,"message":"Request textDocument/foldingRange failed with message: Unrecognized JSON command: getOutliningSpans"}}
```

Updating typescript to 3.6.4 the errors in code are displayed correctly and LSDP4E does not show above error which is strange because it always logs:
```
[Info]	Using typescript v3.5.3 from C:\Users\ninom\.p2\pool\plugins\org.eclipse.wildwebdeveloper_0.5.1.201910151353\language-servers\node_modules\typescript
```

Installing global typescript 3.6.4 did not help, so only with local typescript errors are displayed correctly.
Seems that there some dependencies missing for wildwebdeveloper embedded typescript?
Could it be configured to use global typescript?

**Comment by mickaelistria** [comment]
Wild Web Developer cannot support too old versions of TypeScript as far as I know. This is because the language server uses tsserver which is not functioning properly with older projects and had some API changes I believe.
I don't think this is something we can easily change, as it would be a lot of effort to support outdated stuff. So I'm closing the ticket.
