### ISSUE TITLE
a NPM Launch Configuration

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#340]
On a package.json, one should be able to do "Run As > npm update" (or whichever operation makes sense.

**Comment by AObuchow** [comment]
This is a really good idea!! It would make setting up ESLint in Wild Web Developer much easier, as one could install the dependencies from a package.json without using a terminal.

**Comment by AObuchow** [comment]
@jabby What npm operation do you think is most useful? I tried comparing `npm update` and `npm install` by [reading this](https://stackoverflow.com/questions/12478679/npm-install-vs-update-whats-the-difference) but I'm still not sure. Perhaps having both is ideal?

**Comment by jabby** [comment]
My personal feeling is "There is no operation that are useful with Run as > packageManager operation". 

All JS developers I know use and love cli for their build tools. Me too 😄 .

By the way, this issue is about npm but what about yarn or pnpm users?
If we want to support all main JS package managers, the `Run as` menu will explode some way.

**Comment by jabby** [comment]
FYI I found this gerrit patch on wtp. Maybe there is something useful. 

https://git.eclipse.org/r/c/65109/

**Comment by AObuchow** [comment]
@jabby Good point - I like CLI tools as well ;) However in this case, it's a necessary feature to add since it was available in JSDT (which is planned for removal).

In the end, I worked on a npm install shortcut. However, you have a good point about supporting multiple JS package managers... Maybe they should all be grouped under one launch configuration tab which allows the user to specify their desired package manager and the command to run?

**Comment by AObuchow** [comment]
> FYI I found the following gerrit patches on wtp. Maybe there is something useful.
> 
> * https://git.eclipse.org/r/c/61336/
> * https://git.eclipse.org/r/c/65109/

Thanks for these!

**Comment by mickaelistria** [comment]
@jabby and in CLI, do you use more `npm install` or `npm update`.
Once we have launch configuration, they can then be used as build actions, so for example user can more easily hook auto update of dependencies on change in package.json.
About yarn and others, we'll see. My current impression with the node projects I've worked on (vscode and some language servers) is that even when yarn is in involved, there are some npm tasks wrapping it. So npm is kind of master.
About usage, typical Java developers using Eclipse IDE will most likely look for a Run As action. I think there is a population that will prefer it over CLI (I'm among them)

**Comment by jabby** [comment]
When I use `npm` I think I use more `npm install` but to be fair. I did only this one time without parameters. 
Then if someone else add a new dependency, I use `npm ci`. This is the only way to have exactly the same dependencies than my coworkers. 

If I add new dependencies I will again use `npm install` but this time with parameters (all libraries I want to install or upgrade to a new major version of a dependency). 

By the way, I mostly use `yarn` now because I think install / update processes and lock file are better than the ones from npm.
