### ISSUE TITLE
Multiple "Node.js is not supported" dialogs popping up

### ISSUE THREAD

**Issue by 32kda** [eclipse/wildwebdeveloper#376]
Eclipse IDE for Eclipse Committers
Version: 2019-12 (4.14.0)
Build id: 20191212-1212

Just needed to make a small correction to html/css files, opened an editor and see multiple dialogs saying smth like: "node.js 0.10 is not supported this will result in editors missing key features" popups.
Closed them, but when I pasted a piece of code, they appeared again. Dialogs appear even for plain text editor for me.

Problem screenshot: https://prnt.sc/rfa8x8

Is there some way to turn this off in Preferences?

**Comment by mickaelistria** [comment]
This should have been fixed in recent version and screenshot should be shown only once. See #322 and #323 .
Please first upgrade to latest release, that you can get using https://download.eclipse.org/wildwebdeveloper/releases/0.8.2 .
I'm closing this ticket, feel free to reopen if this still happens after upgrade.
