### ISSUE TITLE
WWD cannot find node at /usr/local/bin/node on macOS

### ISSUE THREAD

**Issue by jpmat296** [eclipse/wildwebdeveloper#418]
Since I've installed node@12 thanks to Homebrew, Node is not installed in standard location. In such case, I think symbolic link in /usr/local/bin is supposed to work. It doesn't for me since I get popup "Node.js version could not be determined".

Here is the symlink:
```
⇒  ls -l /usr/local/bin/node
lrwxr-xr-x  1 jpmat  admin  31  5 May 10:23 /usr/local/bin/node -> /usr/local/opt/node@12/bin/node
```

Here are versions I use:
- Eclipse IDE 2020-03
- WWD snapshot 0.9.1.202005041657 

I applied this workaround:
```
cd /Applications/Eclipse.app/Contents/Eclipse
echo -Dorg.eclipse.wildwebdeveloper.nodeJSLocation=$(which node) >> eclipse.ini
```

**Comment by mickaelistria** [comment]
Does it work with the workaround?
Is node part of the accessible PATH for the Eclipse IDE? IIRC, Mac is specifically annoying on that topic of sharing environment with apps, so maybe node isn't visible in the PATH.
Or is the issue more generally that node as symlink doesn't work (even when visible in PATH)?
Anyway, if there is no better way to handle that, we would welcome a contribution that adds some heuristics of more default locations to look at for node in case it wasn't found otherwise.

**Comment by jpmat296** [comment]
Yes, the workaround works with symlink or not.

Actually PATH cannot be used on MacOS. When Eclipse is started by the icon, PATH is not well defined.

But if I start Eclipse by terminal, then it works:
```
⇒ which node
/usr/local/opt/node@12/bin/node
⇒  cd /Applications/Eclipse.app
⇒  ./Contents/MacOS/eclipse
# Works fine
```

What is not clear to me is why WWD default location detection doesn't work:
https://github.com/eclipse/wildwebdeveloper/blob/4030c2dc9c68dd9fe97c3429fd519153cdb273cc/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java#L95-L98

I will try to debug.

**Comment by jpmat296** [comment]
I've submitted PR.

Issue was not in getDefaultNodePath() but in which(node) code. Please see PR #422 for more details.

**Comment by mickaelistria** [comment]
Should be fixed in upcoming snapshot at https://download.eclipse.org/wildwebdeveloper/snapshots/ (build ongoing at https://ci.eclipse.org/wildwebdeveloper/job/Wildwebdeveloper/job/master/ , takes ~10 minutes). Please try and reopen if issue persists.
Thanks a lot for the contribution!
