### ISSUE TITLE
Update in STS not possible due to missing lsp4e dependency

### ISSUE THREAD

**Issue by gubjack** [eclipse/wildwebdeveloper#428]
Updating WWD in STS fails due to some missing part.

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.lsp4e,0.13.2.202005131306

http://download.eclipse.org/lsp4e/snapshots is listed as repository dependency in STS

**Comment by mickaelistria** [comment]
Wild Web Developer itself seems to work fine. I suggest you restart the IDE then retry updating (as it could be some cache issue), and if the issue is still here, try with a regular Eclipse IDE and reopen with more details in case of failure, or open issue to STS if it's not reproducible anywhere else.
