### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by Dmole** [eclipse/wildwebdeveloper#522]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565410

**Comment by mickaelistria** [comment]
As mentioned in that other bug, the issue seems to be that you are not using the Generic Text Editor, but instead the plain Text Editor, which doesn't have syntax highlighting.
Please try opening with the Generic Text Editor and fix your configuration so that the plain text editor isn't the default.
