### ISSUE TITLE
Completion Template from JSDT ignored by Wild Web Developer.

### ISSUE THREAD

**Issue by kszymko** [eclipse/wildwebdeveloper#630]
I would expect Ctrl+Space while in *.js (JavaScript context) to show templates defined under:

`
Web > Client-side JavaScript > Templates
`

but `arrow`, `forin ` non of them appear. Any suggestions?

**Comment by nitind** [comment]
Client-side JavaScript applies to JavaScript within a web page, and in the case of the preference page you mentioned, in the HTML and JSP Editors, and is unrelated to WWD. Presumably someone more familiar with WWD can point you in the right direction for similar functionality in *.js files.

**Comment by mickaelistria** [comment]
Currently, Wild Web Developer doesn't support templates, and there is no strong plan to add them.
If there are some JS constructs that seem really necessary, then please open a bug to https://github.com/theia-ide/typescript-language-server to get them added directly in the language server, so that will benefit to all its users (including WIld Web Developer).

**Comment by mickaelistria** [comment]
This is actually a dup of #140
