### ISSUE TITLE
main feature.xml has surprisingly old qualifier

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/wildwebdeveloper#712]
Not sure if this is important or even unexpected, but the 0.12.0 version of WWD which was released fairly recently has a qualifier from April (202104061435) - it also requires an older version of the xml feature, perhaps this is why? 

My expectation is that the qualifier of the feature is >= to the qualifier of the highest included feature/plug-in. Certainly in CDT that is what happens, if I change a bundle, all the features that include that bundle directly or indirectly, get a new qualifier automatically.

https://github.com/eclipse/wildwebdeveloper/blob/e1555fd3749702a46ef798e5e2ab151e0e2063c7/org.eclipse.wildwebdeveloper.feature/feature.xml#L28

**Comment by mickaelistria** [comment]
> My expectation is that the qualifier of the feature is >= to the qualifier of the highest included feature/plug-in. 

Yes, IIRC that's the expectation But it's about *included* feature/plugins; a require/import is not an inclusion but a requirement; and a "fun" fact is that the version is ignored when publishing p2 metadata, so in the end it's a 0.0.0.
There were no change to the non-XML bundles since April, so there is technically no change in this particular feature. So it seems all correct, except the useless requires/import@version.
