### ISSUE TITLE
Put embedded nodejs in eclipse folder

### ISSUE THREAD

**Issue by bradhuang9999** [eclipse/wildwebdeveloper#733]
Currently wild web editor will copy a nodejs instance in each workspace.
If we have plenty workspace at one time, it will many nodejs instance in each workspace.
Is it possible to put embedded nodejs in eclipse/plugin folder?

**Comment by vrubezhny** [comment]
Eclipse plugin folder in most cases is a "read-only" (actually it's not a folder at all as most plugins are packed into jars).

For your configuration with many workspaces you can manually install Node.js  or let WWD to do this automatically on one of your workspaces and then set `org.eclipse.wildwebdeveloper.nodeJSLocation` system property to point to the path to Node.js executable. Then use that system property when starting your eclipse instance - if the system property is set correctly and points to a supported version of Node.js - it will be used by WWD instead of installing the Embedded Node.js version to every workspace.

**Comment by mickaelistria** [comment]
I think it would be relatively easy to fix; just adding `Eclipse-BundleShape: dir` to the various `org.eclipse.wildwebdeveloper.embedder.node.<os/arch>` bundles.
@bradhuang9999 Would you be willing to create a pull request for that?

**Comment by mickaelistria** [comment]
Actually `Eclipse-BundleShape: dir` is not enough. As there are execution flags and others, storing in a zip (and then expanding it) is necessary. Maybe this can be put in the `configuration/` area of the Eclipse installation?

**Comment by vrubezhny** [comment]
We can try creating the Node.js Runtime in the following locations, before dropping down to using the Workspace `.metadata/`:
-  Platform Instance Location
- Platform User Location

Both can be absent or not allowed to be written nor to execute a containing binary, so, in case of it's impossible to store a runtime in such a directory, we may still use the Workspace `.metadata`.
