### ISSUE TITLE
Migration from WTP to WWD

### ISSUE THREAD

**Issue by kjsmita6** [eclipse/wildwebdeveloper#809]
Our Eclipse RCP product is previously using WTP (org.eclipse.wst) for our XML editor things. Since moving to the newest Eclipse version with WWD we are running into issues with having both (and I don't think we need both anyways - even if there are no issues). Normally I would just remove it from our feature/product but we have some use of WTP APIs. Is there a migration guide/path from WTP apis to WWD apis? Since WWD uses lsp I didn't see a simple way to just translate the code.

**Comment by mickaelistria** [comment]
Indeed, Wild Web Developer is not meant to be an extensible framework as much as WTP.
However, the lemminx language server it's using for XML supports some extensibility, and so does the Generic Editor and overall Eclipse Platform. What particularly are you trying to add to default XML edition?

**Comment by kjsmita6** [comment]
We mainly use it for validation/editor markers. We have some XML editors that use custom elements/syntax/etc that we validate using wst APIs (Validator, XMLValidationInfo, etc.).

**Comment by mickaelistria** [comment]
You can still add validation using wst APIs. Wild Web Developer does mainly provide extensions to the Generic Editor (via LSP4E), but those custom validations usually do not depend on the editor; so they should work with Generic Editor equally to how they work in the WTP editor.
One example is Eclipse m2e that does have textual editor based on Generic Editor and Wild Web Developer, but still uses WTP APIs to get an internal model of the pom.xml file that is used in order to manipulate the form editor. Both are synchronized as they use the same underlying IDocument.
