### ISSUE TITLE
UI Freeze & Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by jonashungershausen** [eclipse/wildwebdeveloper#88]
Hi,

since the latest install (3 days before) I get these error messages in the log (via `journalctl -f`):
https://gist.github.com/jonashungershausen/e0baca010174924d47cb552b89e598b6
(Couldn't figure out how to properly format it here in the comment).

They go along with some 20 second complete UI freezes of the eclipse instance. 

Using: 
Spring Tool Suite 4 

Version: 4.0.0.RELEASE
Build Id: 201809220817

on Fedora 28

I also installed typescript globally via `yarn global add typescript` but that didn't seem to work.

**Comment by jabby** [comment]
Thanks for the report. I copy your gist here in case the gist disapeared. If you want to share some code/logs you can use 3 back thicks before and after the code block. 

```
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]: Error: Cannot find module 'typescript'
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at Function.Module._resolveFilename (module.js:548:15)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at Function.Module._load (module.js:475:25)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at Module.require (module.js:597:17)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at require (internal/module.js:11:18)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at Object.<anonymous> (/home/jhungershausen/Library/sts-4.0.0.RELEASE/plugins/org.eclipse.wildwebdeveloper_0.1.0.201810092241/language-servers/node_modules/vscode-html-languageserver/out/modes/javascriptMode.js:10:10)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at Module._compile (module.js:653:30)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at Object.Module._extensions..js (module.js:664:10)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at Module.load (module.js:566:32)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]:     at tryModuleLoad (module.js:506:12)
Oct 30 17:07:34 localhost.localdomain Spring Tool Suite 4.desktop[5431]: at Function.Module._load (module.js:498:3)
```
Do you know which version of node is include in your path?

**Comment by mickaelistria** [comment]
I get exact same error on Fedora 29 with

```
$ node --version
v7.10.1
```

**Comment by mickaelistria** [comment]
No `typescript` module seems included.
```
$ ls /home/mistria/eclipse/plugins/org.eclipse.wildwebdeveloper_0.1.0.201810092241/language-servers/node_modules
agent-base            es6-promisify      jsonfile       typescript-language-server  vscode-html-languageservice     vscode-languageserver-protocol-foldingprovider
commander             fs-extra           ms             unique-string               vscode-json-languageserver      vscode-languageserver-types
command-exists        graceful-fs        p-debounce     universalify                vscode-json-languageservice     vscode-nls
crypto-random-string  http-proxy-agent   request-light  vscode-css-languageserver   vscode-jsonrpc                  vscode-uri
debug                 https-proxy-agent  temp-dir       vscode-css-languageservice  vscode-languageserver
es6-promise           jsonc-parser       tempy          vscode-html-languageserver  vscode-languageserver-protocol
```

**Comment by jonashungershausen** [comment]
Thanks for pointing me to the location where the files are. I managed to manually install typescript and that fixed the problem for me.

Looking at the code it seems like it's just a matter of adding the typescript module to the package.json? 
If so, I'd like to take that and submit a PR if possible?

**Comment by mickaelistria** [comment]
> If so, I'd like to take that and submit a PR if possible?

Sure!

**Comment by jabby** [comment]
Normally we don't need to add typescript to the package.json 

I checked the package-lock.json and typescript is listed as depencency. See https://github.com/eclipse/wildwebdeveloper/blob/b082e3a33312c8529a2c65312745aba025b27487/org.eclipse.wildwebdeveloper/language-servers/package-lock.json#L376-L380

I build locally the vuejs branch and there is typescript in the build plugin. I suspect that the problem is not in the dependency but on the CI.

**Comment by mickaelistria** [comment]
I don't think it's CI. A local build gives me same result and misses typescript module.
It can be a build issue though, like an erroneous pom or other file (or even erroneous package.json.lock)
What we can try is from a freassh rep, a local `mvn generate-resources` or `npm install` from language-servers folder and see whether typescript is in.

**Comment by mickaelistria** [comment]
```
mistria@mistria-rh:~/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers$ npm --version
4.2.0
```

**Comment by jabby** [comment]
Thanks Mickael

I tried different version of node + npm on vuejs branch. I did not try with master because it fails on my laptop. 

with node `10.11.0` and npm `6.4.1` : typescript is present 
with node `8.12.0` and npm `6.4.1` : typescript is present
with node `8.11.0` and npm `5.6.0` : typescript is present
with node `7.10.1` and npm `4.2.0` : typescript is present but package-lock.json is not generated

Clearly it's not a problem with node + npm. 
On possibility to solve this problem easily is to fill all CQs for vuejs support and merge the work on master. I will submit an other PR for managing configuration of language servers. 
@mickaelistria what do you think about this proposal?

**Comment by mickaelistria** [comment]
I believe this issue is super important and need to be fully understood. I'd rather avoid using the vuejs inclusion as a "by-the-way" fix for it.

A cause can be that typescript is defined as a "devDependency" in the VSCode language servers so it's not picked transitively during a `npm install` (vue.js LS probably adds it explicit as a runtime dependency). It's bascially a bug in VSCode, but given how we pick some sub-parts of it in a not-so-official way, I don't think we should count on VSCode to fix it for us.
We can explicitly add typescript into the language-servers/package.json as @jonashungershausen suggested.

**Comment by mickaelistria** [comment]
@jonashungershausen I tried your suggestion and it work very well. Would you like to submit the PR, as you're actually the one who made the report and found the best solution?

**Comment by jonashungershausen** [comment]
Yes, I'd like to. Will do it this evening if that's okay. Do you have any pointers to resources I need to set up the development environment?

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by mickaelistria** [comment]
> Yes, I'd like to. Will do it this evening if that's okay.

Sure.

> Do you have any pointers to resources I need to set up the development environment?

Nothing in particular, it's Eclipse plugins as usual. There is a .target file in the repo that you can use. But if you are using your IDE as TP and already have wildwebdeveloper installed, you shouldn't need to use this file specifically nor to switch TP.
Actually, for this change and since your IDE is badly affected by this issue, you don't even need to use the Eclipse IDE, you can edit the package.json manually, then run a `mvn clean verify` and install the plugins from the p2 repository in your IDE to try them.

**Comment by jabby** [comment]
I agree with your last comment. I checked why it happens now and not in previous version of wild web developer. I think the replacement of `javascript-typescript-langserver` by `typescript-language-server` reveal the problem. 

Typescript is also declare as a dependency in `javascript-typescript-langserver` but it's not in `typescript-language-server`. 
I will provide an update of the package.json this evening. I think we should also update the target platform as the build of master failed.  

```
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.lsp4j.generator 0.6.0.v20181107-1212
[ERROR]   Missing requirement: org.eclipse.lsp4j.generator 0.6.0.v20181107-1212 requires 'java.package; org.eclipse.xtend.lib.annotations [2.16.0,3.0.0)' but it could not be found
[ERROR] 
```

**Comment by mickaelistria** [comment]
> I will provide an update of the package.json this evening.

Please leave this to @jonashungershausen 

> I think we should also update the target platform as the build of master failed.

PR welcome ;)

**Comment by jabby** [comment]
Ok. @jonashungershausen if you need some help. Don't hesitate to @ me.
