### ISSUE TITLE
Add ability to enable trace/logging for lemminx extension run within WWD XML LS process?

### ISSUE THREAD

**Issue by scottkurz** [eclipse/wildwebdeveloper#975]
### Discussed in https://github.com/eclipse/wildwebdeveloper/discussions/974

<div type='discussions-op-text'>

<sup>Originally posted by **scottkurz** November 21, 2022</sup>
Hi,  I'm trying to enable trace/logging for a lemminx extension running in XML LS launched from Eclipse 2022-09 using the wildwebdeveloper XML function.   The lemminx XML LS is launched as a separate JVM process in my env.    The extension is now coded with java.util.logging.     

I see there is a "hook" to add a debug port [here](https://github.com/eclipse/wildwebdeveloper/blob/d913c31661c5bff06615baa7799d504e037c22b9/org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java#L92) but I don't see something comparable for say a JUL properties file property.

Also I know we can use the preference of **Language Servers -> Logs** to trace the JSON-RPC calls.. but I'm trying to trace the "internals" not just the JSON-RPC payloads. 

Would this be new function needed?  Or is there another way to accomplish this?  Thank you!

</div>

**Comment by vrubezhny** [comment]
@scottkurz  In theory you can add  `-Dorg.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.log.level=FINER` to your eclipse.ini in order to get some more logging. 

This option was introduced in order to enable the verbosity of LemMinX-Maven extension, so, if latest release of m2e-core is installed (if I'm correct, m2e-core v.2.2.1 should include LemMinX-Maven extension of v. 0.7.1  which is added with more problems logged with 'FINER' level), when LemMinX Maven editor is used, some logging from LemMinX-Maven extension can be seen in Eclipse's logs.

HTH
